import { useEffect, useState } from "react";
import { RiLoginBoxLine, RiLogoutBoxLine, RiTimeLine } from "react-icons/ri";
import { useEmployee } from "../../hooks/useEmployee";
const elapsedFrom = time => { if (!time) return "00:00:00"; const [h, m, s = 0] = time.split(":").map(Number); const start = new Date(); start.setHours(h, m, s, 0); const diff = Math.max(0, Math.floor((Date.now() - start) / 1000)); return [Math.floor(diff / 3600), Math.floor((diff % 3600) / 60), diff % 60].map(n => String(n).padStart(2, "0")).join(":"); };
export default function EmpWorkdayCard({ onCheckIn, onCheckOut, busy }) {
  const { todayRecord, loading } = useEmployee(); const [elapsed, setElapsed] = useState(elapsedFrom(todayRecord?.checkInTime)); const checkedIn = Boolean(todayRecord?.checkInTime); const checkedOut = Boolean(todayRecord?.checkOutTime);
  useEffect(() => { if (!checkedIn || checkedOut) return undefined; const timer = window.setInterval(() => setElapsed(elapsedFrom(todayRecord.checkInTime)), 1000); return () => window.clearInterval(timer); }, [checkedIn, checkedOut, todayRecord?.checkInTime]);
  const status = checkedOut ? "Day completed" : checkedIn ? "Currently working" : "Ready to start";
  return <article className="workday-card"><div className="workday-card__heading"><div><p className="employee-dashboard__eyebrow">Today’s workday</p><h2>{status}</h2></div><span className={`workday-card__status ${checkedIn ? "is-active" : ""}`}><i />{checkedOut ? "Completed" : checkedIn ? "In progress" : "Not checked in"}</span></div><div className="workday-card__body"><div className="workday-card__time"><RiTimeLine /><div><span>Time at work</span><strong>{checkedIn && !checkedOut ? elapsed : todayRecord?.workingHours ? `${todayRecord.workingHours.toFixed(1)}h` : "—"}</strong></div></div><div className="workday-card__events"><div><RiLoginBoxLine /><span>Check in</span><strong>{todayRecord?.checkInTime || "Not recorded"}</strong></div><div><RiLogoutBoxLine /><span>Check out</span><strong>{todayRecord?.checkOutTime || "Pending"}</strong></div></div></div><div className="workday-card__footer"><p>{checkedOut ? "Your attendance has been saved for today." : checkedIn ? "Remember to check out when you finish work." : "Start your workday when you are ready."}</p><div><button className="workday-card__secondary" disabled={busy || checkedIn || loading} onClick={onCheckIn}><RiLoginBoxLine /> {busy ? "Saving…" : "Check in"}</button><button className="workday-card__primary" disabled={busy || !checkedIn || checkedOut || loading} onClick={onCheckOut}><RiLogoutBoxLine /> {busy ? "Saving…" : "Check out"}</button></div></div></article>;
}
